name: Windows-VM

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Disable Windows Defender
      run: |
        Set-MpPreference -DisableRealtimeMonitoring $true
        Set-MpPreference -DisableBehaviorMonitoring $true

    - name: Install Auto Softwares (Office, Chrome, Ngrok)
      run: |
        choco install ngrok -y
        choco install googlechrome -y
        choco install microsoft-office-deployment -y

    - name: Configure ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP & Create RDP User
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user adminuser MyPassword123! /add
        net localgroup Administrators adminuser /add
        net localgroup "Remote Desktop Users" adminuser /add

    - name: Start ngrok Tunnel
      run: ngrok tcp 3389

