name: Windows-VM

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download & Extract ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/b4PvuB3pmWW/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip

    - name: Configure ngrok
      run: .\ngrok\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP & Set Password
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin MyPassword123!

    - name: Start ngrok Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
